import type { PageContent } from "../types";

/** Source: 03 (About Us) merged with 31 (Wellness About). Copy verbatim. Rachel's full story lives on /about/rachel. */
export const about: PageContent = {
  url: "/about",
  title: "About Us — Pathways Within | Wisdom & Wellness Services",
  meta: "Pathways Within is more than a business. It is a living, breathing story built from resilience, community, curiosity, and the belief that even the hardest chapters can lead somewhere meaningful.",
  source: "03-www-pathwayswithin-me-about-us.txt, 31-pathwayswithinwellness-com-about.txt",
  eyebrow: "About Us",
  h1: "Pathways Within is more than a business.",
  intro: [
    "It is a living, breathing story built from resilience, community, curiosity, and the belief that even the hardest chapters can lead somewhere meaningful.",
    "What started as one person’s healing journey has grown into a collaborative mental health and wellness organization for real people living real, wonderfully complicated lives.",
  ],
  heroPhoto: { asset: "ha-ap26-camp-five", alt: "The Pathways Within team together outdoors" },
  heroStop: "wide",
  sections: [
    {
      id: "being-human",
      stop: "cairn",
      layout: "prose",
      blocks: [
        { kind: "p", text: "We know growth rarely follows a neat little timeline. It twists, turns, pauses, doubles back, and occasionally asks you to sit down and catch your breath.", lead: true },
        { kind: "p", text: "That is not failure. That is being human.", lead: true },
      ],
    },
    {
      id: "who-we-are",
      stop: "seated",
      heading: "Who We Are (and Why We’re Here)",
      photo: { asset: "ha-ap-front-desk-team", alt: "The Welcome Team at the front desk" },
      blocks: [
        { kind: "p", text: "At Pathways Within, we bring mental, physical, and spiritual well-being into the same conversation. Our clinicians, wellness practitioners, and support team understand that people are layered—and care should be, too." },
        { kind: "p", text: "You may come to us for therapy, medication management, coaching, acupuncture, massage, wellness support, or simply because something feels off and you are ready to explore it." },
        { kind: "p", text: "You do not need a perfect explanation, a five-year plan, or all the right words before reaching out." },
        { kind: "p", text: "We will meet you where you are, help you sort through the options, and support you in choosing a path that actually fits your life." },
        { kind: "p", text: "Take what you need. Leave what you do not.", lead: true },
        { kind: "p", text: "We will walk with you — and probably remind you to breathe along the way.", lead: true },
      ],
    },
    {
      id: "founder",
      stop: "standing",
      eyebrow: "FOUNDER OF PATHWAYS WITHIN",
      heading: "Meet Rachel: Founder, Therapist & “Patient Zero”",
      photo: { asset: "ha-ap26-rachel-solo", alt: "Rachel Lessard, founder of Pathways Within" },
      blocks: [
        { kind: "p", text: "Hi, I’m Rachel, therapist, founder, lifelong listener, and the original “Patient Zero” behind Pathways Within." },
        { kind: "p", text: "Therapy is not just what I do. It is woven into who I am." },
        { kind: "p", text: "For the more candid version of the story, follow The Wisdom of Wellness on Substack at [@the.wisdom.of.wellness](https://substack.com/@the.wisdom.of.wellness), where I share the behind-the-scenes journey of being a founder, therapist, lifelong learner." },
        { kind: "cta", label: "Read Rachel’s story", href: "/about/rachel" },
      ],
    },
    {
      id: "what-we-believe",
      stop: "labyrinth",
      layout: "wide",
      heading: "What we believe",
      blocks: [
        {
          kind: "list",
          style: "check",
          items: [
            "**The whole picture** — Mental, physical, and emotional well-being are connected—whether or not they coordinate their calendars.",
            "**Your path, your pace** — There is no universal formula, perfect timeline, or gold star for healing the fastest.",
            "**Better together** — Care works best when clients, providers, and support teams communicate and collaborate.",
            "**Community matters** — Growth is personal, but that does not mean you have to do it alone.",
          ],
        },
        { kind: "p", text: "Pathways Within continues to evolve alongside the people and communities we serve. Each new service, provider, and location is added with intention—not just because we can, but because it creates another meaningful way to help people feel seen, supported, and able to move forward." },
        { kind: "list", style: "check", items: ["**Take what you need. Leave what you do not.** — The path does not have to be straight to be taking you somewhere."] },
      ],
    },
    {
      id: "how-pathways-found-its-way",
      stop: "pool",
      heading: "How Pathways Found Its Way",
      photos: [
        { asset: "pr-ap-smt-labyrinth-sign", alt: "The labyrinth sign at the Smithtown office" },
        { asset: "ha-ap26-desk-handshake", alt: "A handshake at the welcome desk" },
        { asset: "ha-ap-group-room-garden-city", alt: "Group room in Garden City" },
      ],
      blocks: [
        { kind: "p", text: "Pathways Within began with one straightforward idea: people are not one-dimensional, so care should not be either." },
        { kind: "p", text: "Mental health, physical health, stress, relationships, lifestyle, and everyday life have a habit of overlapping. We created Pathways Within to stop pretending they do not." },
        { kind: "p", text: "What began as a small private therapy practice has grown into a collaborative mental health and wellness organization across Long Island. Our clinicians, practitioners, and support professionals work across a range of services with one shared goal: making care feel more connected, useful, and human." },
        { kind: "h3", text: "The labyrinth in our logo says a lot about how we see growth." },
        { kind: "p", text: "A labyrinth is not a maze. There are no wrong turns, trick doors, or giant red signs telling you that you have failed. The path may wind, pause, circle inward, or open outward, but it keeps moving." },
        { kind: "p", text: "That same philosophy shapes the Pathways Within experience. Start where you are. Move at your pace. Choose the support that makes sense for you now, knowing that your needs may change along the way." },
      ],
    },
    {
      id: "feeling-better",
      stop: "cairn",
      eyebrow: "Where Feeling Better Gets Personal",
      heading: "Pathways Within Wellness was created for the parts of well-being that cannot always be talked through.",
      photo: { asset: "ha-ap-massage-room", alt: "A massage room at Pathways Within", shape: "arch" },
      blocks: [
        { kind: "p", text: "Sometimes healing looks like reflection and conversation. Sometimes it looks like releasing tension, easing pain, restoring energy, or simply giving your body a chance to exhale." },
        { kind: "p", text: "We believe mental, physical, and emotional wellness are connected—and that caring for yourself should feel personal, approachable, and grounded in what you actually need." },
        { kind: "p", text: "Our work brings together hands-on treatments and holistic services designed to help you feel more comfortable, confident, and at home in your body." },
        { kind: "p", text: "No pressure to become a whole new person.", lead: true },
        { kind: "p", text: "We are simply here to help you feel a little more like yourself.", lead: true },
      ],
    },
    {
      id: "wellness-found-its-way",
      stop: "ivy",
      heading: "How Wellness Found Its Way",
      photo: { asset: "cw-ap-massage-session", alt: "A massage session at Pathways Within", shape: "blob" },
      blocks: [
        { kind: "p", text: "Pathways Within began in the mental health space, but the larger vision was always about the whole person." },
        { kind: "p", text: "Rachel Lessard saw firsthand that emotional healing does not happen separately from the body. Stress can settle into the shoulders. Grief can affect sleep and energy. Physical discomfort can influence mood, confidence, and the way we move through daily life." },
        { kind: "p", text: "The Wellness side of Pathways grew from the belief that these experiences should not be treated as unrelated." },
        { kind: "p", text: "By bringing massage, acupuncture, energy work, and other restorative services into the broader Pathways ecosystem, we created more ways for people to care for themselves—without suggesting that one path works for everyone." },
        { kind: "p", text: "The goal was never to create a one-size-fits-all version of wellness." },
        { kind: "p", text: "It was to create more options, more connection, and more ways to feel supported." },
        { kind: "p", text: "Take what you need. Leave what you do not.", lead: true },
        { kind: "p", text: "And yes, relaxing absolutely counts as productive." },
      ],
    },
    {
      id: "whole-person-wellness",
      stop: "ground",
      layout: "wide",
      heading: "What We Mean by Whole-Person Wellness",
      blocks: [
        { kind: "p", text: "Whole-person wellness means recognizing that your body, mind, emotions, and daily life are constantly influencing one another." },
        { kind: "p", text: "It also means you do not need to wait until something feels unbearable before taking care of yourself." },
        {
          kind: "list",
          style: "pills",
          items: [
            "Physical tension, soreness, or discomfort",
            "Stress and nervous-system regulation",
            "Energy, rest, and recovery",
            "Movement and physical performance",
            "Confidence and body awareness",
            "Emotional well-being",
            "A much-needed pause from everyday life",
          ],
        },
        { kind: "p", text: "You may visit us alongside therapy, as part of a broader wellness plan, or simply because your back has been asking nicely—and is now beginning to raise its voice." },
        { kind: "p", text: "There is no single right reason to begin." },
      ],
    },
    {
      id: "leadership",
      stop: "seated",
      layout: "wide",
      heading: "The People Helping Lead the Way",
      blocks: [
        {
          kind: "person",
          slug: "rachel-lessard",
          eyebrow: "FOUNDER OF PATHWAYS WITHIN",
          name: "Rachel Lessard, LCSW-R",
          paragraphs: [
            "Rachel is a therapist, lifelong listener, and the founder of Pathways Within.",
            "She sets the vision, protects the culture, and keeps asking how Pathways can make care feel more connected, more human, and more useful in real life.",
            "For the behind-the-scenes version of her journey, follow The Wisdom of Wellness on Substack at [@the.wisdom.of.wellness](https://substack.com/@the.wisdom.of.wellness).",
          ],
          cta: { label: "Meet Rachel", href: "/about/rachel" },
        },
        {
          kind: "person",
          slug: "ksusha-cascio",
          eyebrow: "CHIEF OPERATING OFFICER",
          name: "Ksusha Cascio, LCSW",
          paragraphs: [
            "Ksusha is the person who helps turn big ideas into clear plans, strong systems, and an organization that actually knows where the metaphorical keys are.",
            "With a passion for developing the clinicians in the practice, her thoughtful, judgment-free approach keeps teams connected, operations moving, and growth grounded in the experience of the people doing the work so they can deliver the best level of patient care.",
          ],
        },
        {
          kind: "person",
          slug: "joe-bush",
          eyebrow: "CLINICAL DIRECTOR, NASSAU",
          name: "Joseph “Joe” Bush, LCSW",
          paragraphs: [
            "Joe brings a relational, practical lens to clinical leadership and a strong belief that no one should have to navigate life’s challenges alone.",
            "Drawing from his work with adolescents, adults, families, and relationships, he supports the Nassau clinical team in delivering care that is compassionate, approachable, and rooted in real-world needs.",
          ],
        },
        {
          kind: "person",
          slug: "lee-wasser",
          eyebrow: "CLINICAL DIRECTOR, SUFFOLK",
          name: "Lee Wasser, LMHC-D",
          paragraphs: [
            "Lee brings a broad, adaptable clinical perspective to his leadership of the Suffolk team.",
            "He encourages curiosity, inclusivity, and flexibility, helping clinicians expand their skills while keeping treatment centered on the person in front of them, not a one-size-fits-all playbook.",
          ],
        },
        {
          kind: "person",
          slug: "christine-cervo",
          eyebrow: "WELLNESS LEADER AND HANDS-ON HEALER",
          name: "Christine Cervo",
          paragraphs: [
            "Christine helps bring the Wellness vision into the day-to-day client and provider experience. As a licensed massage therapist, she brings hands-on expertise, intuition, and a strong understanding of how thoughtful, personalized care should feel.",
          ],
          cta: { label: "Read Christine’s bio", href: "/team/christine-cervo" },
        },
      ],
    },
    {
      id: "better-together",
      stop: "standing",
      heading: "Better Together",
      photo: { asset: "ha-ap26-camp-three", alt: "Three members of the Pathways Within team" },
      blocks: [
        { kind: "p", text: "Rachel has the big ideas. Ksusha builds the structure around it. Joe brings a deeply relational and practical lens to clinical leadership, while Lee champions adaptability, individuality, and continued learning." },
        { kind: "p", text: "They do not lead in separate lanes. They collaborate across locations, disciplines, and decisions to make sure Pathways Within stays connected in how it grows, how it supports its team, and how it cares for people. Different strengths. Shared direction. Much better together – even better with coffee!" },
        { kind: "h3", text: "Meet the Wellness Management Team" },
        { kind: "p", text: "Pathways Within Wellness is led by Rachel Lessard and Christine Cervo, who bring two complementary perspectives to the organization: the larger vision of whole-person care and the hands-on understanding of what clients and practitioners need." },
        { kind: "h3", text: "Leading Wellness Together" },
        { kind: "p", text: "Rachel brings the whole-person vision. Christine brings the hands-on perspective. Together, they help keep Pathways Within Wellness welcoming, connected, and centered on care that feels personal." },
        { kind: "p", text: "Our management team helps guide the vision and experience, while our providers bring their own areas of expertise, personalities, and approaches to care." },
        { kind: "p", text: "Each practitioner offers something different, but all share the same goal: to help people feel supported, respected, and more connected to themselves." },
        { kind: "p", text: "Because wellness is not about fixing who you are." },
        { kind: "p", text: "Sometimes it is simply about creating enough space to hear what your mind and body have been trying to tell you." },
        { kind: "cta", label: "Meet the whole team", href: "/team", secondary: true },
      ],
    },
    {
      id: "wondering",
      stop: "ground",
      layout: "wide",
      heading: "A Few Things You May Be Wondering",
      blocks: [
        {
          kind: "faq",
          items: [
            { q: "What is Pathways Within?", a: ["Pathways Within is a collaborative mental health and wellness organization for the whole person, not just the one concern that brought you through the door."] },
            { q: "What does “whole-person care” mean?", a: ["It means we recognize that mental health, physical health, relationships, stress, lifestyle, and daily responsibilities are all part of the same life. We look at the broader picture and help you explore the support that may be most useful."] },
            { q: "Do I need to know exactly what kind of support I need?", a: ["No, and honestly, most people do not. You may know that something feels off, heavy, stuck, or simply ready to change. Our Welcome Team can help you sort through the options and find a place to begin."] },
            { q: "Do I have to use more than one service?", a: ["Not at all. Some clients work with one provider, while others build a mix of services over time. Take what feels helpful. Leave what does not. Your care should fit you not the other way around."] },
            { q: "Can my providers communicate with one another?", a: ["Yes, when it is helpful and with your permission. Members of your care team will collaborate to create a more connected healing experience, while your privacy, comfort, and consent stay at the center of the process."] },
            { q: "Is Pathways Within only for people in crisis?", a: ["Definitely not. People come to us during hard seasons, but also for personal growth, stronger relationships, stress support, physical well-being, performance goals, or simply because life could use a tune-up."] },
            { q: "How do I get started?", a: ["Contact our Welcome Team and tell us a little about what is bringing you in. You do not need a polished explanation or all the answers. We will help you find a starting point that feels manageable, supportive, and right for you."] },
          ],
        },
        { kind: "cta", label: "All frequently asked questions", href: "/faq", secondary: true },
      ],
    },
  ],
  closing: {
    heading: "Take what you need. Leave what you do not.",
    text: ["Contact our Welcome Team and tell us a little about what is bringing you in."],
    cta: { label: "Contact Us", href: "/contact" },
  },
};
